name: Backend CI/CD

on:
  schedule:
    - cron: "0 6 * * *" # Daily at 6 AM UTC
  workflow_dispatch:

defaults:
  run:
    working-directory: Backend/

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Restore dependencies
        run: dotnet restore DDDNetCore.csproj

      - name: Build application
        run: dotnet build DDDNetCore.csproj -c Release -o ./dist

      - name: Run tests
        run: dotnet test DDDNetCore.csproj

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: ./dist

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy artifacts
        run: |
          scp -P ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa -r ./dist ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/deploy-Backend
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            echo "Deployment started: $(date)"
            DEPLOY_DIR=~/deploy-Backend
            APP_NAME=DDDNetCore

            # Navigate to deployment directory
            cd $DEPLOY_DIR

            # Setup environment
            export ASPNETCORE_ENVIRONMENT="Production"
            export ASPNETCORE_URLS="https://localhost:5001"

            # Database migration
            echo "Running migrations..."
            dotnet ef database update

            # Stop existing app
            echo "Stopping existing instance..."
            pkill -f $APP_NAME || echo "No running instance found."

            # Start application
            echo "Starting new instance..."
            nohup ./dist/$APP_NAME > app.log 2>&1 &

            # Verify deployment
            if pgrep -f $APP_NAME > /dev/null; then
              echo "Deployment successful: $(date)"
            else
              echo "Deployment failed: $(date)"
              exit 1
            fi
          EOF
