name: Backend CI/CD

on:
  schedule:
    - cron: "0 6 * * *" # Daily at 6 AM UTC
  workflow_dispatch:

defaults:
  run:
    working-directory: Backend/

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0"

      - name: Restore dependencies
        run: dotnet restore DDDNetCore.csproj

      - name: Build application
        run: dotnet publish DDDNetCore.csproj -c Release -o ./dist --self-contained -r linux-x64

      - name: Run tests
        run: dotnet test DDDNetCore.csproj

      - name: Archive production artifacts
        run: tar -czf dist.tar.gz -C ./dist .

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy artifacts
        run: |
          # Upload compressed artifacts
          scp -P ${{ secrets.SSH_PORT }} -i ~/.ssh/id_rsa dist.tar.gz ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/deploy-Backend

          # Execute deployment steps on the server
          ssh -i ~/.ssh/id_rsa -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            echo "Deployment started: $(date)"
            DEPLOY_DIR=~/deploy-Backend
            APP_NAME=DDDNetCore

            # Extract files
            echo "Extracting artifacts..."
            tar -xzf $DEPLOY_DIR/dist.tar.gz -C $DEPLOY_DIR && rm $DEPLOY_DIR/dist.tar.gz

            # Navigate to deployment directory
            cd $DEPLOY_DIR

            # Setup environment
            export ASPNETCORE_ENVIRONMENT="Production"
            export ASPNETCORE_URLS="https://localhost:5001"

            # Run migrations if there are pending changes
            echo "Checking for pending migrations..."
            if dotnet ef migrations list | grep -q 'Pending'; then
              echo "Running migrations..."
              dotnet ef database update
            else
              echo "No pending migrations."
            fi

            # Stop existing app
            echo "Stopping existing instance..."
            pkill -f $APP_NAME || echo "No running instance found."

            # Start application
            echo "Starting new instance..."
            nohup ./dist/$APP_NAME > app.log 2>&1 &

            # Verify deployment
            sleep 5
            if pgrep -f $APP_NAME > /dev/null; then
              echo "Deployment successful: $(date)"
            else
              echo "Deployment failed: $(date)"
              exit 1
            fi
          EOF
